branches:
  only:
  - master

language: node_js
node_js:
  - 10
  - 12
  - stable

script:
  - npm run lint
  - npm test

before_deploy:
- bash scripts/deploy-live-viewer.sh
- openssl aes-256-cbc -K $encrypted_3767330e5762_key -iv $encrypted_3767330e5762_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  edge:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
